---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pipeline-run-on-github-pr-merge-template
spec:
  params:
    - name: git-repo-url
      description: The URL of the git repository
    - name: git-revision
      description: The git revision (commit SHA) to checkout after merge
    - name: pr-id
      description: The ID of the Pull Request
    - name: pr-title
      description: The title of the Pull Request
    - name: head-branch
      description: The source branch of the PR
    - name: base-branch
      description: The target branch of the PR
    - name: pr-action
      description: The action that triggered the PR event
    - name: pr-merged
      description: Boolean indicating if the PR was merged
    - name: pr-author
      description: The GitHub login of the PR author
  resourcetemplates:
    # Use 'when' expressions to conditionally create the PipelineRun
    # This ensures the pipeline only runs if the PR was merged to 'main'.
    - apiVersion: tekton.dev/v1
      kind: PipelineRuns
      metadata:
        name: dotnet-demo-app-pipeline-run
        annotations:
          # The event we are targeting as seen from the webhook payload
          # this can be an array too, i.e: [pull_request, push]
          # pipelinesascode.tekton.dev/on-event: "[pupush]"

          # The branch or tag we are targeting (ie: main, refs/tags/*)
          pipelinesascode.tekton.dev/on-target-branch: "[main]"

          pipelinesascode.tekton.dev/pipeline: https://github.com/col1985/tkn-pipelines-as-code/blob/main/pipelines/dotnet-build-and-push-pipeline.yaml

          # How many runs we want to keep.
          pipelinesascode.tekton.dev/max-keep-runs: "5"
      spec:
        when:
          # Condition 1: Ensure the PR action is 'closed'
          - input: $(tt.params.pr-action)
            operator: in
            values: ["closed"]
          # Condition 2: Ensure the PR was actually merged (not just closed without merge)
          - input: $(tt.params.pr-merged)
            operator: in
            values: ["true"] # Note: The 'merged' field is a boolean in GitHub payload,
                             # but Tekton params convert it to string 'true' or 'false'.
            # Condition 3: Ensure the target branch is 'main'
          - input: $(tt.params.base-branch)
            operator: in
            values: ["main"]

        pipelineRef:
          name:  dotnet-build-test-bake-push
        params:
          # The variable with brackets are special to Pipelines as Code
          # They will automatically be expanded with the events from Github.
          - name: version
            value: v0.0.2
          - name: base-image
            value: registry.redhat.io/rhel8/dotnet-90:latest
          - name: project-name
            value: ConsoleAppPAC
          - name: context-dir
            value: "."
          - name: release-dir
            value: "./publish"
          - name: dockerfile
            value: ./Dockerfile
          - name: repo_url
            value: "{{ repo_url }}"
          - name: revision
            value: "{{ revision }}"
          - name: registry-url
            value: quay.io/cbennett/dotnet-demo-app
          - name: package
            value: "."
          - name: sonar-host-url
            value: https://sonarcloud.io
          - name: sonar-project-key
            value: col1985_dotnet-demo-app
          - name: sonar-organization
            value: col1985
          - name: src-to-scan
            value: .
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 500Mi
          # This workspace will inject secret to help the git-clone task to be able to
          # checkout the private repositories
          - name: basic-auth
            secret:
              secretName: "{{ git_auth_secret }}"
          - name: dockerconfig-ws
            secret:
              secretName: quay-secret
